Лабораторная работа 2, Сахаровой Дарьи, 6313-100503D 
"Нормы, разложение матриц"
Вариант 7

In [52]:
import numpy as np

Задание 1 - Скалярное произведение

In [89]:
# Генерация случайных вещественных чисел из интервала (2,4)
# матрица размером 8 на 8
# используется равн.распределение
A = np.random.uniform(2, 4, (8, 8))

# Нахождение скалярного произведения 3 строки на 8 столбец
# Используя срезы матриц
scalar_product = np.dot(A[2,:], A[:,7])

print("\t\tМатрица:\n",A)
print("\nСкалярное произведение 3 строки на 8 столбец:", scalar_product)

		Матрица:
 [[2.0253 2.952  2.8804 3.3155 3.9087 2.868  2.5554 3.0515]
 [2.4306 2.1902 2.3833 3.3065 3.7742 3.1767 3.1218 3.4847]
 [3.6522 2.4232 2.707  3.8981 2.203  2.1024 2.3351 2.5916]
 [2.9128 2.9017 3.4746 3.9237 3.6563 3.1552 3.7873 3.0646]
 [2.218  2.1429 2.3255 2.9631 3.7211 2.7581 3.1523 2.3282]
 [3.0149 2.3665 3.652  2.3319 2.243  2.1843 2.404  2.8904]
 [3.3813 2.4382 3.7786 3.0266 2.9706 3.7605 3.8624 2.5355]
 [3.5541 3.0811 3.9488 2.3341 3.2669 3.4475 3.7188 3.4872]]

Скалярное произведение 3 строки на 8 столбец: 64.7139863583093


Задание 2 - Произведение двух матриц тремя способами

(целые числа из отрезка(!) [-2,6])

In [93]:
matrix_1 = np.random.randint(-2, 7, (3, 6))
matrix_2 = np.random.randint(-2, 7, (6, 5))

print("\tМатрица 1:\n", matrix_1, "\n\n\tМатрица 2:\n", matrix_2)

res_1 = np.zeros((3,5), dtype = int)
for i in range(3):
    for j in range(5):
        for p in range(6):
            res_1[i,j] = res_1[i,j] + matrix_1[i,p]*matrix_2[p,j]
print("\n\tСкалярный (поэлементный) алгоритм:\n", res_1)

# Способ 2
# for k in range(3):
#     for j in range(5):
#         res_2[k,j] = sum(matrix_1[k,i]*matrix_2[i,j] for i in range(6))

res_2 = np.zeros((3,5), dtype = int)
for k in range(3):
    for j in range(5):
        res_2[k,j] = np.dot(matrix_1[k,:], matrix_2[:,j])
print("\n\tВекторный алгоритм:\n", res_2)

res_3 = np.dot(matrix_1, matrix_2)
print("\n\tС помощью np.dot:\n", res_3)


	Матрица 1:
 [[ 5  5  1  6  5  5]
 [ 4  1 -2  2  3  5]
 [ 4  1  0  0 -1  3]] 

	Матрица 2:
 [[ 5  6  5  6 -1]
 [-1  6 -2  0  1]
 [-1  2 -2 -1  1]
 [-1 -1  4  1  1]
 [ 5  6  6  6 -2]
 [ 6  2  4  6  2]]

	Скалярный (поэлементный) алгоритм:
 [[68 96 87 95  7]
 [64 52 68 76  1]
 [32 30 24 36  5]]

	Векторный алгоритм:
 [[68 96 87 95  7]
 [64 52 68 76  1]
 [32 30 24 36  5]]

	С помощью np.dot:
 [[68 96 87 95  7]
 [64 52 68 76  1]
 [32 30 24 36  5]]


Задание 3 - Вычисление нормы вектора-строки

In [91]:
# вторая норма - корень из суммы квадратов всех чисел
def norm_2(vector):
    norm_sum = 0
    for i in vector:
        norm_sum += i**2
    return norm_sum**(1/2)

vector_task_3 = np.random.randint(-100, 100, 9)
print("Вектор - ", vector_task_3)
print("\nС помощью собственной функции - ", norm_2(vector_task_3))
print("С помощью linalg.norm - ", np.linalg.norm(vector_task_3, ord=2))

Вектор -  [-64  40   8  22  25  16 -37  51  43]

С помощью собственной функции -  113.77170122662314
С помощью linalg.norm -  113.77170122662314


Задание 4 - Вычисление нормы матрицы

In [97]:
# бесконечная норма матрицы - максимум из суммы модулей по всем СТРОКАМ
def norm_inf(matrix):
    max_norm = 0
    for row in matrix:
        row_norm = sum(abs(i) for i in row) # вычисление суммы каждой строки
        if row_norm > max_norm:
            max_norm = row_norm
    return max_norm

# создание матрицы 
matrix_task_4 = np.random.randint(-2, 7, (3, 3))

print("\tМатрица :\n", matrix_task_4)
print("\nС помощью собственной функции - ", norm_inf(matrix_task_4))
print("С помощью linalg.norm - ", np.linalg.norm(matrix_task_4, ord=np.inf))

	Матрица :
 [[ 4  6 -1]
 [ 3  0  4]
 [ 3 -2 -1]]

С помощью собственной функции -  11
С помощью linalg.norm -  11.0


Задание 5 - отражение Хаусхолдера для вектора

In [57]:

v = np.zeros(9)
v[2:] = vector_task_3[2:]

# Вычисляем норму вектора нормали
norm_v = np.linalg.norm(v)

# Определяем вектор отражения
u = v / (v[2] + norm_v)

# Вычисляем матрицу отражения Хаусхолдера
H = np.eye(9) - 2 * np.outer(u, u)

# Применяем матрицу отражения к вектору-строке
reflected_vector = np.dot(H, vector_task_3)

print("Вектор-строка:", vector_task_3)
print("Отражение Хаусхолдера:", H)
print("Отраженный вектор-строка:", reflected_vector)

Вектор-строка: [-49  46 -57  18 -99  -5 -48   0  82]
Отражение Хаусхолдера: [[ 1.          0.          0.          0.          0.          0.
   0.          0.          0.        ]
 [ 0.          1.          0.          0.          0.          0.
   0.          0.          0.        ]
 [ 0.          0.          0.24474903  0.23850031 -1.31175168 -0.06625009
  -0.63600082  0.          1.0865014 ]
 [ 0.          0.          0.23850031  0.92468411  0.41423737  0.02092108
   0.20084236  0.         -0.3431057 ]
 [ 0.          0.         -1.31175168  0.41423737 -1.27830556 -0.11506594
  -1.104633    0.          1.88708137]
 [ 0.          0.         -0.06625009  0.02092108 -0.11506594  0.99418859
  -0.05578955  0.          0.09530714]
 [ 0.          0.         -0.63600082  0.20084236 -1.104633   -0.05578955
   0.46442036  0.          0.91494854]
 [ 0.          0.          0.          0.          0.          0.
   0.          1.          0.        ]
 [ 0.          0.          1.0865014  -0.343

Задание 6 -  LU разложение матрицы

In [58]:
def LU_decomposition(matrix):
    n = matrix.shape[0]
    L = np.eye(n)
    U = np.copy(matrix)

    for k in range(n-1):
        for i in range(k+1, n):
            L[i, k] = U[i, k] / U[k, k]
            for j in range(k, n):
                U[i, j] -= L[i, k] * U[k, j]
                
    return L, U

L, U = LU_decomposition(matrix_task_4)

print("Исходная матрица:\n", matrix_task_4)
print("\nМатрица L:\n", L)
print("\nМатрица U:\n", U)

# Проверка с помощью перемножения матриц
result = np.dot(L, U)
print("\nРезультат перемножения матриц L и U (проверка):\n", result)

Исходная матрица:
 [[-2  0 -2]
 [ 3 -2  0]
 [ 6  0  2]]

Матрица L:
 [[ 1.   0.   0. ]
 [-1.5  1.   0. ]
 [-3.  -0.   1. ]]

Матрица U:
 [[-2  0 -2]
 [ 0 -2 -3]
 [ 0  0 -4]]

Результат перемножения матриц L и U (проверка):
 [[-2.  0. -2.]
 [ 3. -2.  0.]
 [ 6.  0.  2.]]


Задание 7 - QR разложение матрицы

In [112]:
np.set_printoptions(precision=4, suppress=True) # 4 знака после зарятой

matrix_7 = matrix_task_4.astype(float) # меняем тип с int на float

# метод Грама-Шмидта
def gram_schmidt(matrix):
    n = matrix.shape[1]
    Q = np.zeros_like(matrix)
    R = np.zeros((n, n))

    for j in range(n):
        v = matrix[:, j]
        for i in range(j):
            R[i, j] = np.dot(Q[:, i], matrix[:, j])
            v -= R[i, j] * Q[:, i]
        R[j, j] = np.linalg.norm(v)
        Q[:, j] = v / R[j, j]

    return Q, R

print("Матрица исходная:\n", matrix_7)

# находим QR разложение
Q_1, R_1 = gram_schmidt(matrix_7)
print("\nМатрица Q (Грама-Шмидта):\n", Q_1)
print("\nМатрица R (Грама-Шмидта):\n", R_1)

# Проверка с помощью перемножения матриц
print("\nРезультат перемножения матриц Q и R (Грама-Шмидта):\n", np.dot(Q_1, R_1))

Матрица исходная:
 [[ 4.  6. -1.]
 [ 3.  0.  4.]
 [ 3. -2. -1.]]

Матрица Q (Грама-Шмидта):
 [[ 0.686   0.7033 -0.1864]
 [ 0.5145 -0.2877  0.8078]
 [ 0.5145 -0.65   -0.5592]]

Матрица R (Грама-Шмидта):
 [[ 5.831   3.087   0.8575]
 [ 0.      5.52   -1.2042]
 [ 0.      0.      3.9768]]

Результат перемножения матриц Q и R (Грама-Шмидта):
 [[ 4.  6. -1.]
 [ 3. -0.  4.]
 [ 3. -2. -1.]]


In [110]:
matrix_7 = matrix_task_4.astype(float) # меняем тип с int на float

# метод Хаусхолдера (отражений)
def householder(matrix):
    (r, c) = np.shape(matrix)
    Q = np.identity(r)
    R = np.copy(matrix)

    for i in range(r - 1):
        x = R[i:, i]
        e = np.zeros_like(x)
        e[0] = np.linalg.norm(x)
        u = x - e
        v = u / np.linalg.norm(u)
        Q_i = np.identity(r)
        Q_i[i:, i:] -= 2.0 * np.outer(v, v)
        R = np.dot(Q_i, R)
        Q = np.dot(Q, Q_i)

    return Q, R

print("Матрица исходная:\n", matrix_7)

# находим QR разложение
Q_2, R_2 = householder(matrix_7)
print("\nМатрица Q (Хаусхолдера):\n", Q_2)
print("\nМатрица R (Хаусхолдера):\n", R_2)

# Проверка с помощью перемножения матриц
print("\nРезультат перемножения матриц Q и R (Хаусхолдера):\n", np.dot(Q_2, R_2))

Матрица исходная:
 [[ 4.  6. -1.]
 [ 3.  0.  4.]
 [ 3. -2. -1.]]

Матрица Q (Хаусхолдера):
 [[ 0.686   0.7033 -0.1864]
 [ 0.5145 -0.2877  0.8078]
 [ 0.5145 -0.65   -0.5592]]

Матрица R (Хаусхолдера):
 [[ 5.831   3.087   0.8575]
 [ 0.      5.52   -1.2042]
 [-0.      0.      3.9768]]

Результат перемножения матриц Q и R (Хаусхолдера):
 [[ 4.  6. -1.]
 [ 3.  0.  4.]
 [ 3. -2. -1.]]


In [114]:
matrix_7 = matrix_task_4.astype(float) # меняем тип с int на float

# метод Гивенса (вращений)
def givens(matrix):
    (r, c) = np.shape(matrix)
    Q = np.identity(r)
    R = np.copy(matrix)
    (rows, cols) = np.tril_indices(r, -1, c)

    for (row, col) in zip(rows, cols):
        if R[row, col] != 0:
            r_ = np.hypot(R[col, col], R[row, col])
            c = R[col, col]/r_
            s = -R[row, col]/r_
            G = np.identity(r)
            G[[col, row], [col, row]] = c
            G[row, col] = s
            G[col, row] = -s
            R = np.dot(G, R)
            Q = np.dot(Q, G.T)

    return Q, R


print("Матрица исходная:\n", matrix_7)

# находим QR разложение
Q_3, R_3 = givens(matrix_7)
print("\nМатрица Q (Гивенса):\n", Q_3)
print("\nМатрица R (Гивенса):\n", R_3)

# Проверка с помощью перемножения матриц
result_method_3 = np.dot(Q_3, R_3)
print("\nРезультат перемножения матриц Q и R (Гивенса):\n", np.dot(Q_3, R_3))


Матрица исходная:
 [[ 4.  6. -1.]
 [ 3.  0.  4.]
 [ 3. -2. -1.]]

Матрица Q (Гивенса):
 [[ 0.686   0.7033 -0.1864]
 [ 0.5145 -0.2877  0.8078]
 [ 0.5145 -0.65   -0.5592]]

Матрица R (Гивенса):
 [[ 5.831   3.087   0.8575]
 [-0.      5.52   -1.2042]
 [ 0.     -0.      3.9768]]

Результат перемножения матриц Q и R (Гивенса):
 [[ 4.  6. -1.]
 [ 3.  0.  4.]
 [ 3. -2. -1.]]


In [115]:
matrix_7 = matrix_task_4.astype(float) # меняем тип с int на float

print("Матрица исходная:\n", matrix_7)

# Проверка с помощью функции np.linalg.qr
Q_np, R_np = np.linalg.qr(matrix_7)
print("\n\tNumPy\n\nМатрица Q:\n", Q_np)
print("\nМатрица R:\n", R_np)
print("\n", np.dot(Q_np, R_np))

Матрица исходная:
 [[ 4.  6. -1.]
 [ 3.  0.  4.]
 [ 3. -2. -1.]]

	NumPy

Матрица Q:
 [[-0.686   0.7033  0.1864]
 [-0.5145 -0.2877 -0.8078]
 [-0.5145 -0.65    0.5592]]

Матрица R:
 [[-5.831  -3.087  -0.8575]
 [ 0.      5.52   -1.2042]
 [ 0.      0.     -3.9768]]

 [[ 4.  6. -1.]
 [ 3.  0.  4.]
 [ 3. -2. -1.]]
