Лабораторная работа 2, Сахаровой Дарьи, 6313-100503D 
"Решение СЛАУ"
Вариант 7

In [1]:
import numpy as np

Задание 1 - решить систему AX = B

In [28]:
# Создать произвольную нижнетреугольную матрицу А 5 порядка 
# (не унитреугольную), вектор B произвольный. Решить систему AX = B.

# Создание нижнетреугольной матрицы A (не унитреугольной)
A = np.tril(np.random.randint(1, 10, size=(5, 5)))

# Создание вектора B
B = np.random.randint(1, 10, size=(5,))

# Нахождение обратной матрицы A^(-1)
A_inv = np.linalg.inv(A)
# Решение 
X_1 = np.dot(A_inv, B)

# Проверка решения
X_2 = np.linalg.solve(A, B)

print("Матрица A:\n", A)
print("Вектор B:\n", B)
print("\nРешение с помощью обратной матрицы:\n", X_1)
print("Решение с помощью np.linalg.solve:\n", X_2)

Матрица A:
 [[5 0 0 0 0]
 [7 2 0 0 0]
 [5 3 2 0 0]
 [8 5 8 5 0]
 [4 5 4 8 6]]
Вектор B:
 [9 4 2 3 1]

Решение с помощью обратной матрицы:
 [ 1.8        -4.3         2.95       -2.7         4.18333333]
Решение с помощью np.linalg.solve:
 [ 1.8        -4.3         2.95       -2.7         4.18333333]


Задание 2 - Решить систему, используя LU разложение

In [50]:
# функция разложения из 1-ой части лабораторной
def LU_decomposition(matrix):
    n = matrix.shape[0]
    L = np.eye(n)
    U = np.copy(matrix)

    for k in range(n-1):
        for i in range(k+1, n):
            L[i, k] = U[i, k] / U[k, k]
            for j in range(k, n):
                U[i, j] -= L[i, k] * U[k, j]
                
    return L, U


# Алгоритм:
# Находим L и U =>  
# L*U * X = B
# Пусть Y = U*X,  тогда L*Y=B,  и находим  Y = (L^-1)*B
# Затем находим X = (U^-1)*Y

# Задание системы уравнений
matrix_A = np.array([[14.4, -5.3, 14.3, -12.7],
                   [23.4, -14.2, -5.4, 2.1],
                   [6.3, -13.2, -6.5, 14.3],
                   [5.6, 8.8, -6.7, -23.8]
                   ], dtype=float)

vector_B = np.array([[14.4], [6.6], [9.4], [7.3]])

print("Левая часть(матрица):\n",matrix_A, "\nПравая часть(вектор)\n",vector_B,"\nдолжно получиться: х1~=-1,73; х2~=-3,5; х3~=-0,266; х4~=-1,93")



L, U = LU_decomposition(matrix_A)

# нахождение обратных матриц
U_inverse = np.linalg.inv(U)
L_inverse = np.linalg.inv(L)

# решение Y = (L^-1)*B
Y = L_inverse.dot(vector_B)

# решение X = (U^-1)*Y
X_lu = U_inverse.dot(Y)

print("\nМатрица L:\n", L)
print("\nМатрица U:\n", U)

print("\nРезультат:\n", X_lu)

Левая часть(матрица):
 [[ 14.4  -5.3  14.3 -12.7]
 [ 23.4 -14.2  -5.4   2.1]
 [  6.3 -13.2  -6.5  14.3]
 [  5.6   8.8  -6.7 -23.8]] 
Правая часть(вектор)
 [[14.4]
 [ 6.6]
 [ 9.4]
 [ 7.3]] 
должно получиться: х1~=-1,73; х2~=-3,5; х3~=-0,266; х4~=-1,93

Матрица L:
 [[ 1.          0.          0.          0.        ]
 [ 1.625       1.          0.          0.        ]
 [ 0.4375      1.94742729  1.          0.        ]
 [ 0.38888889 -1.94382302 -1.57922089  1.        ]]

Матрица U:
 [[ 14.4         -5.3         14.3        -12.7       ]
 [  0.          -5.5875     -28.6375      22.7375    ]
 [  0.           0.          43.01319911 -24.42337808]
 [  0.           0.           0.         -13.23334423]]

Результат:
 [[-1.73206342]
 [-3.50403348]
 [-0.26601589]
 [-1.93498921]]


Задание 3 - ту же систему, используя QR разложение методом Хаусхолдера

In [49]:
# метод Хаусхолдера (отражений) из 1 части лабораторной 
def householder(matrix):
    (r, c) = np.shape(matrix)
    Q = np.identity(r)
    R = np.copy(matrix)

    for i in range(r - 1):
        x = R[i:, i]
        e = np.zeros_like(x)
        e[0] = np.linalg.norm(x)
        u = x - e
        v = u / np.linalg.norm(u)
        Q_i = np.identity(r)
        Q_i[i:, i:] -= 2.0 * np.outer(v, v)
        R = np.dot(Q_i, R)
        Q = np.dot(Q, Q_i)

    return Q, R


# Алгоритм:
# Находим Q и R =>  
# Q*R * X = B
# Пусть Y = R*X,  тогда Q*Y=B,  и находим  Y = (Q^-1)*B
# Затем находим X = (R^-1)*Y

print("Левая часть(матрица):\n", matrix_A, "\nПравая часть(вектор)\n", vector_B)


# находим QR разложение
Q, R = householder(matrix_A)

# нахождение обратных матриц
R_inverse = np.linalg.inv(R)
Q_inverse = np.linalg.inv(Q)

# решение Y = (Q^-1)*B
Y = Q_inverse.dot(vector_B)

# решение X = (R^-1)*Y
X_qr = R_inverse.dot(Y)

print("\nМатрица Q:\n", Q)
print("\nМатрица U:\n", R)

print("\nРезультат:\n", X_qr)


Левая часть(матрица):
 [[ 14.4  -5.3  14.3 -12.7]
 [ 23.4 -14.2  -5.4   2.1]
 [  6.3 -13.2  -6.5  14.3]
 [  5.6   8.8  -6.7 -23.8]] 
Правая часть(вектор)
 [[14.4]
 [ 6.6]
 [ 9.4]
 [ 7.3]]

Матрица Q:
 [[ 0.50104918  0.15443761  0.78576053  0.32814499]
 [ 0.81420492 -0.10647157 -0.29396188 -0.48920402]
 [ 0.21920902 -0.62850771 -0.30136416  0.68271891]
 [ 0.19485246  0.75484495 -0.45315168  0.43231375]]

Матрица U:
 [[ 2.87396938e+01 -1.53961278e+01  3.79266393e-02 -6.15629384e+00]
 [ 9.27570243e-16  1.56323142e+01  1.81124324e+00 -2.91379178e+01]
 [ 6.58638970e-15  5.73790333e-17  1.78187530e+01 -4.12097613e+00]
 [ 8.93754454e-16  5.47703831e-16 -1.74251105e-15 -5.72095671e+00]]

Результат:
 [[-1.73206342]
 [-3.50403348]
 [-0.26601589]
 [-1.93498921]]


In [59]:
print("Проверка непосредственной подстановкой:\n", np.dot(matrix_A, X_qr))

X_solve = np.linalg.solve(matrix_A, vector_B)
print("\nРешение с помощью np.linalg.solve:\n", X_solve)
print("\n\t!! РЕШЕНИЯ МЕТОДАМИ LU И QR РАЗЛОЖЕНИЙ ДАЮТ ОДИНАКОВЫЕ ВЕРНЫЕ РЕЗ-ТЫ")

Проверка непосредственной подстановкой:
 [[14.4]
 [ 6.6]
 [ 9.4]
 [ 7.3]]

Решение с помощью np.linalg.solve:
 [[-1.73206342]
 [-3.50403348]
 [-0.26601589]
 [-1.93498921]]

	!! РЕШЕНИЯ МЕТОДАМИ LU И QR РАЗЛОЖЕНИЙ ДАЮТ ОДИНАКОВЫЕ ВЕРНЫЕ РЕЗ-ТЫ


Задание 4 - Метод Зейделя (точность до 10^-3)

In [96]:
from prettytable import PrettyTable

# х1 = 1.575  х2 = 1.5724  х3 = 1.57697

# Задание системы уравнений
A = np.array([[2.15, -1.18, 0.57],[1.24, 0.62, -0.95],
              
              [1.72, -0.83, 1.57]])
B = np.array([2.43,1.43,  3.88])

# Задание начальные приближения для решения системы
x_prev = np.zeros(3)
x_curr = np.zeros(3)

# Задание точности
epsilon = 1e-3

# Инициализация таблицы
table = PrettyTable()
table.field_names = ["№ итерации", "x_1", "x_2", "x_3"]

# Итерационный процесс
iteration = 1
while True:
    # вычисление нового значения x_curr для каждого 
    # уравнения системы по ф-ле метода Зейделя
    for i in range(len(A)):
        x_curr[i] = (B[i] - np.dot(A[i, :i], x_curr[:i]) - np.dot(A[i, i+1:], x_prev[i+1:])) / A[i, i]
    
    # Проверка достижения заданной точности
    if np.all(np.abs(x_curr - x_prev) < epsilon):
        break
    
    # Обновление предыдущих значений
    x_prev = x_curr.copy()
    
    # Запись текущих значений в таблицу
    table.add_row([iteration, round(x_curr[0], 4), round(x_curr[1], 4), round(x_curr[2], 4)])
    
    iteration += 1

# Вывод таблицы
print(table)

+------------+--------+---------+--------+
| № итерации |  x_1   |   x_2   |  x_3   |
+------------+--------+---------+--------+
|     1      | 1.1302 |  0.046  | 1.2574 |
|     2      | 0.8221 |  2.589  | 2.9394 |
|     3      | 1.7719 |  3.2666 | 2.2571 |
|     4      | 2.3247 |  1.1156 | 0.5143 |
|     5      | 1.6061 | -0.1177 | 0.6495 |
|     6      | 0.8934 |  1.5148 | 2.2934 |
|     7      | 1.3536 |  3.1133 | 2.6343 |
|     8      | 2.1405 |  2.0618 | 1.2163 |
|     9      | 1.9394 |  0.2914 | 0.5007 |
|     10     | 1.1574 |  0.7589 | 1.6045 |
|     11     | 1.1213 |  2.5223 | 2.5763 |
|     12     | 1.8316 |  2.5909 | 1.8345 |
|     13     | 2.0659 |  0.9857 | 0.7292 |
|     14     | 1.4779 |  0.468  | 1.0996 |
|     15     | 1.0955 |  1.8003 | 2.2229 |
|     16     | 1.529  |  2.6545 | 2.1996 |
|     17     | 2.004  |  1.6689 | 1.1582 |
|     18     | 1.7391 |  0.6028 | 0.8847 |
|     19     | 1.2265 |  1.2091 | 1.7668 |
|     20     | 1.3254 |  2.3629 | 2.2685 |
|     21   

Задание 5 - Найти псевдорешение системы

In [97]:
# X = ( A_transp * A )^-1 * A_transp * B

# Задание системы уравнений
matrix_A_5 = np.array([[14.4, -5.3, 14.3],
                   [23.4, -14.2, -5.4],
                   [6.3, -13.2, -6.5],
                   [5.6, 8.8, -6.7]
                   ], dtype=float)

vector_B_5 = np.array([[14.4], [6.6], [9.4], [7.3]])

print("Левая часть(матрица):\n", matrix_A_5, "\nПравая часть(вектор)\n", vector_B_5)

# транспонируем матрицу
matrix_A_5_transp = matrix_A_5.transpose()

# A_transp * A 
tmp_1 = np.dot(matrix_A_5_transp, matrix_A_5)

# ( A_transp * A )^-1
tmp_2 = np.linalg.inv(tmp_1)

# ( A_transp * A )^-1 * A_transp * B
tmp_3 = np.dot(np.dot(tmp_2, matrix_A_5_transp), vector_B_5)

print("\nПсевдорешение:\n", tmp_3)


Левая часть(матрица):
 [[ 14.4  -5.3  14.3]
 [ 23.4 -14.2  -5.4]
 [  6.3 -13.2  -6.5]
 [  5.6   8.8  -6.7]] 
Правая часть(вектор)
 [[14.4]
 [ 6.6]
 [ 9.4]
 [ 7.3]]

Псевдорешение:
 [[0.58622104]
 [0.05084708]
 [0.18149266]]
