In [1]:
import numpy as np

1.Создать квадратную матрицу из случайных целых чисел из[-7,-2]   размера   9.   
Найти   и   вычислить   минор   4   порядка,   распо-ложенный на пересечении 1, 2, 3, 4 строк и 2, 3, 8, 9 столбцов. Ис-пользовать срезы матрицы

In [3]:
# Создаем квадратную матрицу 9x9 с случайными целыми числами в диапазоне [-7, -2]
matrix = np.random.randint(-7, -1, (9, 9))

# Выводим исходную матрицу
print("Исходная матрица:")
print(matrix)

# Используем срезы для получения минора 4-го порядка
# Сначала выбираем строки 1, 2, 3, 4 и столбцы 2, 3, 8, 9
minor = matrix[0:4, 1:3]
minor = np.concatenate((minor, matrix[0:4, 7:9]), axis=1)

# Выводим минор
print("Минор 4-го порядка:")
print(minor)

Исходная матрица:
[[-6 -2 -5 -4 -3 -5 -2 -7 -6]
 [-4 -3 -7 -4 -2 -7 -3 -6 -3]
 [-7 -2 -3 -4 -3 -4 -7 -4 -7]
 [-3 -6 -2 -4 -7 -3 -2 -3 -3]
 [-6 -6 -4 -4 -2 -4 -6 -2 -4]
 [-3 -3 -2 -6 -6 -2 -4 -4 -7]
 [-4 -7 -5 -7 -6 -3 -4 -7 -3]
 [-2 -7 -5 -4 -2 -6 -5 -2 -4]
 [-5 -7 -7 -6 -4 -6 -2 -2 -6]]
Минор 4-го порядка:
[[-2 -5 -7 -6]
 [-3 -7 -6 -3]
 [-2 -3 -4 -7]
 [-6 -2 -3 -3]]


Создать   две   матрицы   из   случайных   вещественных   чиселподходящего   размера.
Найти   их   произведение   тремя   способами:
используя   векторный   алгоритм   умножения   матриц;
используя матричный алгоритм, записав матрицу С по столбцам;
 проверив спомощью функции np.dot

In [4]:
# Создаем две случайные матрицы подходящего размера, например, 3x4 и 4x2.
matrix1 = np.random.rand(3, 4)
matrix2 = np.random.rand(4, 2)

# Выводим исходные матрицы
print("Исходная матрица 1:")
print(matrix1)
print("Исходная матрица 2:")
print(matrix2)

# 1. Используем векторный алгоритм умножения матриц
result1 = np.dot(matrix1, matrix2)

# 2. Используем матричный алгоритм, записывая матрицу C по столбцам
result2 = np.zeros((matrix1.shape[0], matrix2.shape[1]))
for i in range(matrix2.shape[1]):
    result2[:, i] = np.dot(matrix1, matrix2[:, i])

# 3. Используем функцию np.dot
result3 = np.dot(matrix1, matrix2)

# Выводим результаты
print("Результат с использованием векторного алгоритма:")
print(result1)
print("Результат с использованием матричного алгоритма, записанный по столбцам:")
print(result2)
print("Результат с использованием функции np.dot:")
print(result3)

Исходная матрица 1:
[[0.36818527 0.06898439 0.69927373 0.25787692]
 [0.49880884 0.45069315 0.25802015 0.2179523 ]
 [0.84064134 0.29094192 0.9499443  0.7168581 ]]
Исходная матрица 2:
[[0.48879643 0.66204922]
 [0.22345186 0.20252989]
 [0.83534518 0.37221061]
 [0.94655686 0.51064529]]
Результат с использованием векторного алгоритма:
[[1.02361244 0.6496889 ]
 [0.76636434 0.62884899]
 [1.94799234 1.33510993]]
Результат с использованием матричного алгоритма, записанный по столбцам:
[[1.02361244 0.6496889 ]
 [0.76636434 0.62884899]
 [1.94799234 1.33510993]]
Результат с использованием функции np.dot:
[[1.02361244 0.6496889 ]
 [0.76636434 0.62884899]
 [1.94799234 1.33510993]]


Создать вектор-строку 1x8 из случайных целых чисел. Вы-числить   норму  ‖x‖3  самостоятельно   написанной   функцией   ипроверить результат с помощью linalg.norm()

In [5]:
# Создаем случайную вектор-строку 1x8 с целыми числами
x = np.random.randint(1, 10, 8)

# Выводим исходный вектор
print("Исходный вектор:")
print(x)

# Самостоятельно написанная функция для вычисления L3-нормы
def custom_l3_norm(vector):
    norm = np.sum(np.abs(vector) ** 3) ** (1/3)
    return norm

# Вычисляем L3-норму с помощью самостоятельно написанной функции
custom_norm_result = custom_l3_norm(x)

# Вычисляем L3-норму с использованием linalg.norm()
numpy_norm_result = np.linalg.norm(x, ord=3)

# Выводим результаты
print("L3-норма, вычисленная самостоятельно:", custom_norm_result)
print("L3-норма, вычисленная с использованием linalg.norm():", numpy_norm_result)

Исходный вектор:
[1 8 8 7 1 5 3 3]
L3-норма, вычисленная самостоятельно: 11.567965519315505
L3-норма, вычисленная с использованием linalg.norm(): 11.567965519315505


Создать матрицу из случайных целых чисел. Найти спек-тральную норму матрицы с помощью самостоятельно написанногоалгоритма   (можно   использовать   функцию   для   нахождения   соб-ственных значений), проверить результат с помощью linalg.norm()

In [6]:
# Создаем матрицу случайных целых чисел, например, 3x3
matrix = np.random.randint(-10, 10, (3, 3))

# Выводим исходную матрицу
print("Исходная матрица:")
print(matrix)

# Самостоятельно написанный алгоритм для вычисления спектральной нормы
def custom_spectral_norm(matrix):
    eigenvalues = np.linalg.eigvals(matrix)  # Находим собственные значения
    spectral_norm = np.max(np.abs(eigenvalues))  # Максимальное собственное значение по модулю
    return spectral_norm

# Вычисляем спектральную норму с помощью самостоятельно написанного алгоритма
custom_norm_result = custom_spectral_norm(matrix)

# Вычисляем спектральную норму с использованием linalg.norm()
numpy_norm_result = np.linalg.norm(matrix, ord=2)

# Выводим результаты
print("Спектральная норма, вычисленная самостоятельно:", custom_norm_result)
print("Спектральная норма, вычисленная с использованием linalg.norm():", numpy_norm_result)

Исходная матрица:
[[ 9 -3 -3]
 [-1 -8 -3]
 [-1  0 -2]]
Спектральная норма, вычисленная самостоятельно: 9.390451926780232
Спектральная норма, вычисленная с использованием linalg.norm(): 10.65695476156651


Для вектора, созданного в третьем пункте, найти отраже-ние   Хаусхолдера,   которое   обнуляет   его   координаты   с   4   по   8.Например,     вектор     (1,2,3,4,5,6,7,8)     переводит     в     вектор(1,2,c,0,0,0,0,0)

In [7]:
# Создаем исходный вектор v=x−∣∣x∣∣⋅e k

x = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# Выбираем диапазон координат, которые нужно обнулить (с 4 по 8)
k = 4
v = x.copy()
v[k-1:] = 0

# Вычисляем ||x||
norm_x = np.linalg.norm(x)

# Вычисляем вектор отражения
v = v - norm_x * np.eye(len(x))[:, k-1]

# Выводим вектор отражения
print("Вектор отражения Хаусхолдера:")
print(v)

Вектор отражения Хаусхолдера:
[  1.           2.           3.         -14.28285686   0.
   0.           0.           0.        ]


Для матрицы, созданной в 4 пункте, найти LU разложениесамостоятельно   написанной   функцией   и   проверить   результат   спомощью перемножения матриц.

In [8]:
# Функция для вычисления LU-разложения
def lu_decomposition(matrix):
    n = matrix.shape[0]
    L = np.eye(n)  # Создаем начальную матрицу L как единичную
    U = matrix.copy()  # Создаем копию исходной матрицы для U

    for k in range(n):
        for j in range(k+1, n):
            if U[k, k] == 0:
                raise ValueError("LU-разложение невозможно: ведущий элемент равен нулю.")
            factor = U[j, k] / U[k, k]
            L[j, k] = factor
            U[j, k:] -= factor * U[k, k:]

    return L, U

# Создаем матрицу (предполагая, что у вас уже есть созданная матрица)
matrix = np.array([[2, 3, 1], [4, 7, 7], [1, 5, 5]], dtype=float)

# Вычисляем LU-разложение
L, U = lu_decomposition(matrix)

# Проверяем результат, перемножив матрицы L и U
result = np.dot(L, U)

# Выводим результаты
print("Матрица L:")
print(L)
print("Матрица U:")
print(U)
print("Результат перемножения L и U:")
print(result)

Матрица L:
[[1.  0.  0. ]
 [2.  1.  0. ]
 [0.5 3.5 1. ]]
Матрица U:
[[  2.   3.   1.]
 [  0.   1.   5.]
 [  0.   0. -13.]]
Результат перемножения L и U:
[[2. 3. 1.]
 [4. 7. 7.]
 [1. 5. 5.]]


Для матрицы, созданной в 4 пункте, найти QR разложениевсеми рассмотренными методами, проверить результат с помощьюперемножения матриц и с помощью функции np.linalg.qr.

In [9]:
# Функция для вычисления QR-разложения с помощью метода Грама-Шмидта
def gram_schmidt_qr(matrix):
    n, m = matrix.shape
    Q = np.zeros((n, m))
    R = np.zeros((m, m))

    for j in range(m):
        v = matrix[:, j]
        for i in range(j):
            R[i, j] = np.dot(Q[:, i], matrix[:, j])
            v = v - R[i, j] * Q[:, i]
        R[j, j] = np.linalg.norm(v)
        Q[:, j] = v / R[j, j]

    return Q, R

# Создаем матрицу (предполагая, что у вас уже есть созданная матрица)
matrix = np.array([[2, 3, 1], [4, 7, 7], [1, 5, 5]], dtype=float)

# Вычисляем QR-разложение с помощью метода Грама-Шмидта
Q_gs, R_gs = gram_schmidt_qr(matrix)

# Вычисляем QR-разложение с использованием функции np.linalg.qr
Q_np, R_np = np.linalg.qr(matrix)

# Проверяем результаты с помощью перемножения матриц и сравнения с библиотечной функцией
result_gs = np.dot(Q_gs, R_gs)
result_np = np.dot(Q_np, R_np)

# Выводим результаты
print("Матрица Q (метод Грама-Шмидта):")
print(Q_gs)
print("Матрица R (метод Грама-Шмидта):")
print(R_gs)
print("Результат перемножения Q и R (метод Грама-Шмидта):")
print(result_gs)
print("Матрица Q (с использованием np.linalg.qr):")
print(Q_np)
print("Матрица R (с использованием np.linalg.qr):")
print(R_np)
print("Результат перемножения Q и R (с использованием np.linalg.qr):")
print(result_np)

Матрица Q (метод Грама-Шмидта):
[[ 0.43643578 -0.21968739 -0.87250287]
 [ 0.87287156 -0.13181243  0.46980924]
 [ 0.21821789  0.96662451 -0.13423121]]
Матрица R (метод Грама-Шмидта):
[[4.58257569 8.51049772 7.63762616]
 [0.         3.25137334 3.69074811]
 [0.         0.         1.74500574]]
Результат перемножения Q и R (метод Грама-Шмидта):
[[2. 3. 1.]
 [4. 7. 7.]
 [1. 5. 5.]]
Матрица Q (с использованием np.linalg.qr):
[[-0.43643578  0.21968739  0.87250287]
 [-0.87287156  0.13181243 -0.46980924]
 [-0.21821789 -0.96662451  0.13423121]]
Матрица R (с использованием np.linalg.qr):
[[-4.58257569 -8.51049772 -7.63762616]
 [ 0.         -3.25137334 -3.69074811]
 [ 0.          0.         -1.74500574]]
Результат перемножения Q и R (с использованием np.linalg.qr):
[[2. 3. 1.]
 [4. 7. 7.]
 [1. 5. 5.]]
