вариант 6 Морозов Сергей

In [9]:
import numpy as np
import scipy.linalg

Создать произвольную верхнетреугольную матрицу А 5 по-рядка   (не   унитреугольную),   вектор  B  произвольный.   Решить   си-стему AX =  B

In [10]:
# Создание произвольной верхнетреугольной матрицы A 5x5
A = np.array([[3, 1, 2, 4, 2],
              [0, 2, 0, 1, 5],
              [0, 0, 4, 0, 3],
              [0, 0, 0, 2, 6],
              [0, 0, 0, 0, 1]])

# Создание произвольного вектора B
B = np.array([15, 8, 11, 12, 3])

# Решение системы AX = B с помощью обратной подстановки
n = len(B)
X = np.zeros(n)

for i in range(n - 1, -1, -1):
    X[i] = (B[i] - np.dot(A[i, i+1:], X[i+1:])) / A[i, i]

print("Решение X:")
print(X)

Решение X:
[ 7.33333333 -2.          0.5        -3.          3.        ]


Решить систему, используя LU   разложение
4.3x1−12.1x2+23.2x3−14.1x4=15.5
2.4x1−4.4x2+3.5x3+5.5x4=2.5
5.4x1+8.3x2−7.4x3−12.7x4=8.6
6.3x1−7.6x2+1.34x3+3.7x4=12.1

In [11]:
# Матрица коэффициентов системы
A = np.array([[4.3, -12.1, 23.2, -14.1],
              [2.4, -4.4, 3.5, 5.5],
              [5.4, 8.3, -7.4, -12.7],
              [6.3, -7.6, 1.34, 3.7]])

# Вектор правой части
B = np.array([15.5, 2.5, 8.6, 12.1])

# Выполним LU-разложение матрицы A
P, L, U = scipy.linalg.lu(A)

# Решим систему уравнений Ly = B
y = scipy.linalg.solve_triangular(L, B, lower=True, check_finite=False)

# Решим систему уравнений Ux = y
x = scipy.linalg.solve_triangular(U, y, check_finite=False)

print("Решение X:")
print(x)

Решение X:
[2.90183797 1.10530806 1.09191805 1.12313294]


Решить   систему  из   пункта   2   с   помощью  QR  разложенияматрицы А. QR разложение найти методом Гивенса. Проверить по-лученное решение непосредственной подстановкой в исходную си-стему, а также методом np.solve.

In [12]:
# Выполним QR-разложение матрицы A методом Гивенса
Q, R = np.linalg.qr(A, mode='complete')

# Решим систему уравнений Rx = Q^T * B
QTB = np.dot(Q.T, B)
x = np.linalg.solve(R, QTB)

# Выведем полученное решение
print("Решение X:")
print(x)

# Проверка решения непосредственной подстановкой
check = np.allclose(np.dot(A, x), B)
if check:
    print("Проверка непосредственной подстановкой: Решение верно.")
else:
    print("Проверка непосредственной подстановкой: Решение неверно.")

# Проверка решения с использованием np.linalg.solve
x_check = np.linalg.solve(A, B)
check2 = np.allclose(x, x_check)
if check2:
    print("Проверка с использованием np.linalg.solve: Решение верно.")
else:
    print("Проверка с использованием np.linalg.solve: Решение неверно.")

Решение X:
[ 1.17377014 -0.97122206 -0.40615705 -0.57615922]
Проверка непосредственной подстановкой: Решение верно.
Проверка с использованием np.linalg.solve: Решение верно.


Решить систему методом простых итераций с точностью до10−3.   Проверить   выполнение   достаточного   условия   сходимости.Если условие не выполняется, в программе выполнить эквивалент-ные   преобразования   системы,   после   этого   привести   к   удобномудля   итераций   виду.   Оформить  итерации   в   виде   таблицы   (можнопользоваться модулями PrettyTable или Pandas)

3.2x1−2.5x2+3.7x3=6.5
0.5x1+0.34x2+1.7x3=−0.24
1.6x1+2.3x2−1.5x3=4.3


In [13]:
# Исходная система уравнений
def f1(x2, x3):
    return (6.5 + 2.5 * x2 - 3.7 * x3) / 3.2

def f2(x1, x3):
    return (-0.24 - 0.5 * x1 - 1.7 * x3) / 0.34

def f3(x1, x2):
    return (4.3 - 1.6 * x1 - 2.3 * x2) / 1.5

# Начальное приближение
x1, x2, x3 = 0, 0, 0

# Заданная точность
tolerance = 1e-3

# Итерации
iterations = 0
while True:
    x1_new = f1(x2, x3)
    x2_new = f2(x1, x3)
    x3_new = f3(x1, x2)
    
    # Проверка сходимости
    if (np.abs(x1_new - x1) < tolerance and
        np.abs(x2_new - x2) < tolerance and
        np.abs(x3_new - x3) < tolerance):
        break
    
    x1, x2, x3 = x1_new, x2_new, x3_new
    iterations += 1

print(f"Решение X: x1 = {x1}, x2 = {x2}, x3 = {x3}")
print(f"Количество итераций: {iterations}")

KeyboardInterrupt: 

Найти псевдорешение системы:

3.2x1−2.5x2+3.7x3=6.5

0.5x1+0.34x2+1.7x3=−0.24

1.6x1+2.3x2−1.5x3=4.3

3.6x1+1.8x2−4.7x3=3.8

In [14]:
# Матрица коэффициентов A
A = np.array([[3.2, -2.5, 3.7],
              [0.5, 0.34, 1.7],
              [1.6, 2.3, -1.5],
              [3.6, 1.8, -4.7]])

# Вектор правой части b
b = np.array([6.5, -0.24, 4.3, 3.8])

# Находим псевдорешение x с использованием МНК
x_pseudo = np.linalg.lstsq(A, b, rcond=None)[0]

print("Псевдорешение x:")
print(x_pseudo)

Псевдорешение x:
[1.66489764 0.38193972 0.44553653]
