In [97]:
import numpy as np

1.Создать квадратную матрицу из случайных целых чисел из[-7,-2]   размера   9.   
Найти   и   вычислить   минор   4   порядка,   распо-ложенный на пересечении 1, 2, 3, 4 строк и 2, 3, 8, 9 столбцов. Ис-пользовать срезы матрицы

In [98]:
# Создаем квадратную матрицу 9x9 с случайными целыми числами в диапазоне [-7, -2]
matrix = np.random.randint(-7, -1, (9, 9))

# Выводим исходную матрицу
print("Исходная матрица:")
print(matrix)

# Используем срезы для получения минора 4-го порядка
# Сначала выбираем строки 1, 2, 3, 4 и столбцы 2, 3, 8, 9
minor = matrix[0:4, 1:3]
minor = np.concatenate((minor, matrix[0:4, 7:9]), axis=1)

# Выводим минор
print("Минор 4-го порядка:")
print(minor)

Исходная матрица:
[[-7 -7 -6 -6 -5 -5 -4 -7 -5]
 [-2 -4 -6 -6 -5 -4 -5 -7 -5]
 [-3 -6 -6 -2 -7 -6 -4 -3 -5]
 [-4 -3 -4 -7 -2 -4 -5 -7 -4]
 [-2 -5 -2 -7 -5 -2 -3 -4 -6]
 [-2 -7 -3 -6 -3 -7 -4 -3 -4]
 [-4 -7 -4 -6 -4 -2 -5 -6 -7]
 [-3 -7 -2 -2 -3 -6 -7 -5 -6]
 [-4 -7 -3 -5 -7 -7 -3 -4 -3]]
Минор 4-го порядка:
[[-7 -6 -7 -5]
 [-4 -6 -7 -5]
 [-6 -6 -3 -5]
 [-3 -4 -7 -4]]


2Создать   две   матрицы   из   случайных   вещественных   чиселподходящего   размера.
Найти   их   произведение   тремя   способами:
используя   векторный   алгоритм   умножения   матриц;
используя матричный алгоритм, записав матрицу С по столбцам;
 проверив спомощью функции np.dot

In [99]:
# Создаем две случайные матрицы подходящего размера, например, 3x4 и 4x2.
matrix1 = np.random.rand(3, 4)
matrix2 = np.random.rand(4, 2)

# Выводим исходные матрицы
print("Исходная матрица 1:")
print(matrix1)
print("Исходная матрица 2:")
print(matrix2)

# 1. Используем векторный алгоритм умножения матриц
result1 = np.zeros((3,2), dtype = float)
for k in range(3):
    for j in range(2):
        result1[k,j] = np.dot(matrix1[k,:], matrix2[:,j])


# 2. Используем матричный алгоритм, записывая матрицу C по столбцам
result2 = np.zeros((matrix1.shape[0], matrix2.shape[1]))
for i in range(matrix2.shape[1]):
    result2[:, i] = np.dot(matrix1, matrix2[:, i])

# 3. Используем функцию np.dot
result3 = np.dot(matrix1, matrix2)

# Выводим результаты
print("Результат с использованием векторного алгоритма:")
print(result1)
print("Результат с использованием матричного алгоритма, записанный по столбцам:")
print(result2)
print("Результат с использованием функции np.dot:")
print(result3)

Исходная матрица 1:
[[0.68190907 0.69172284 0.90636642 0.72634669]
 [0.14981137 0.10346803 0.41830947 0.36487209]
 [0.66955636 0.99993415 0.41875406 0.52903248]]
Исходная матрица 2:
[[0.37721289 0.81280471]
 [0.12933959 0.81775224]
 [0.79890112 0.22711423]
 [0.59367253 0.24272238]]
Результат с использованием векторного алгоритма:
[[1.50200128 1.50206612]
 [0.62069573 0.38994525]
 [1.0305115  1.58542998]]
Результат с использованием матричного алгоритма, записанный по столбцам:
[[1.50200128 1.50206612]
 [0.62069573 0.38994525]
 [1.0305115  1.58542998]]
Результат с использованием функции np.dot:
[[1.50200128 1.50206612]
 [0.62069573 0.38994525]
 [1.0305115  1.58542998]]


3Создать вектор-строку 1x8 из случайных целых чисел. Вы-числить   норму  ‖x‖3  самостоятельно   написанной   функцией   ипроверить результат с помощью linalg.norm()

In [100]:
# Создаем случайную вектор-строку 1x8 с целыми числами
x = np.random.randint(1, 10, 8)

# Выводим исходный вектор
print("Исходный вектор:")
print(x)

# Самостоятельно написанная функция для вычисления L3-нормы
def custom_l3_norm(vector):
    norm = np.sum(np.abs(vector) ** 3) ** (1/3)
    return norm

# Вычисляем L3-норму с помощью самостоятельно написанной функции
custom_norm_result = custom_l3_norm(x)

# Вычисляем L3-норму с использованием linalg.norm()
numpy_norm_result = np.linalg.norm(x, ord=3) 

# Выводим результаты
print("L3-норма, вычисленная самостоятельно:", custom_norm_result)
print("L3-норма, вычисленная с использованием linalg.norm():", numpy_norm_result)

Исходный вектор:
[9 7 3 6 6 5 4 9]
L3-норма, вычисленная самостоятельно: 13.479163099958948
L3-норма, вычисленная с использованием linalg.norm(): 13.479163099958948


4Создать матрицу из случайных целых чисел. Найти спек-тральную норму матрицы с помощью самостоятельно написанногоалгоритма   (можно   использовать   функцию   для   нахождения   соб-ственных значений), проверить результат с помощью linalg.norm()

In [101]:
# Создаем матрицу случайных целых чисел, например, 3x3
matrix = np.random.randint(-10, 10, (3, 3))

# Выводим исходную матрицу
print("Исходная матрица:")
print(matrix)

# Самостоятельно написанный алгоритм для вычисления спектральной нормы
def custom_spectral_norm(matrix):
    for elem in matrix:
        max=0
        r_norm = sum(abs(i) for i in elem) # вычисление суммы каждой строки
        if r_norm > max:
            max= r_norm
    return max
    

# Вычисляем спектральную норму с помощью самостоятельно написанного алгоритма
custom_norm_result = custom_spectral_norm(matrix)

# Вычисляем спектральную норму с использованием linalg.norm()
numpy_norm_result = np.linalg.norm(matrix, ord=2)

# Выводим результаты
print("Спектральная норма, вычисленная самостоятельно:", custom_norm_result)
print("Спектральная норма, вычисленная с использованием linalg.norm():", numpy_norm_result)

Исходная матрица:
[[-10   6   4]
 [  5 -10   3]
 [ -6   6   6]]
Спектральная норма, вычисленная самостоятельно: 18
Спектральная норма, вычисленная с использованием linalg.norm(): 18.110969757176928


5Для вектора, созданного в третьем пункте, найти отраже-ние   Хаусхолдера,   которое   обнуляет   его   координаты   с   4   по   8.Например,     вектор     (1,2,3,4,5,6,7,8)     переводит     в     вектор(1,2,c,0,0,0,0,0)

In [102]:
# v=x−∣∣x∣∣⋅e k
#||x|| - это норма (длина) вектора x, которая может быть вычислена как корень из суммы квадратов его компонент: ||x|| = sqrt(x[0]^2 + x[1]^2 + ... + x[n-1]^2).
#e_k - это вектор, у которого k-я компонента равна 1, а все остальные компоненты равны 0. Этот вектор обозначает k-й базисный вектор (например, вектор, который имеет 1 на k-й позиции и 0 во всех остальных)
# Выбираем диапазон координат, которые нужно обнулить (с 4 по 8)
k = 4
v = x.copy()
v[k-1:] = 0

# Вычисляем ||x||
norm_x = np.linalg.norm(x)

# Вычисляем вектор отражения
v = v - norm_x * np.eye(len(x))[:, k-1]

# Выводим вектор отражения
print("Вектор отражения Хаусхолдера:")
print(v)


    

Вектор отражения Хаусхолдера:
[  9.           7.           3.         -18.24828759   0.
   0.           0.           0.        ]


6Для матрицы, созданной в 4 пункте, найти LU разложениесамостоятельно   написанной   функцией   и   проверить   результат   спомощью перемножения матриц.

In [103]:
# Функция для вычисления LU-разложения
def lu_decomposition(matrix):
    # Получим размерность матрицы
    n = matrix.shape[0]
    L = np.eye(n)
    U = np.copy(matrix)

    for k in range(n-1):
        for i in range(k+1, n):
            L[i, k] = U[i, k] / U[k, k]
            for j in range(k, n):
                U[i, j] -= L[i, k] * U[k, j]
                
    return L, U




L, U = lu_decomposition(matrix)

# Проверяем результат, перемножив матрицы L и U
result = np.dot(L, U)

# Выводим результаты
print(matrix)
print("Матрица L:")
print(L)
print("Матрица U:")
print(U)
print("Результат перемножения L и U:")
print(result)

[[-10   6   4]
 [  5 -10   3]
 [ -6   6   6]]
Матрица L:
[[ 1.          0.          0.        ]
 [-0.5         1.          0.        ]
 [ 0.6        -0.28571429  1.        ]]
Матрица U:
[[-10   6   4]
 [  0  -7   5]
 [  0   0   4]]
Результат перемножения L и U:
[[-10.           6.           4.        ]
 [  5.         -10.           3.        ]
 [ -6.           5.6          4.97142857]]


7Для матрицы, созданной в 4 пункте, найти QR разложение

In [104]:
# Функция для вычисления QR-разложения с помощью метода Грама-Шмидта
def gram_schmidt_qr(matrix):
    n, m = matrix.shape
    Q = np.zeros((n, m))
    R = np.zeros((m, m))

    for j in range(m):
        v = matrix[:, j]
        for i in range(j):
            R[i, j] = np.dot(Q[:, i], matrix[:, j])
            v = v - R[i, j] * Q[:, i]
        R[j, j] = np.linalg.norm(v)
        Q[:, j] = v / R[j, j]

    return Q, R



# Вычисляем QR-разложение с помощью метода Грама-Шмидта
Q_gs, R_gs = gram_schmidt_qr(matrix)

# Вычисляем QR-разложение с использованием функции np.linalg.qr
Q_np, R_np = np.linalg.qr(matrix)

# Проверяем результаты с помощью перемножения матриц и сравнения с библиотечной функцией
result_gs = np.dot(Q_gs, R_gs)


# Выводим результаты
print("Начальная матрица:")
print(matrix)
print("Матрица Q (метод Грама-Шмидта):")
print(Q_gs)
print("Матрица R (метод Грама-Шмидта):")
print(R_gs)
print("Результат перемножения Q и R (метод Грама-Шмидта):")
print(result_gs)
print("Матрица Q (с использованием np.linalg.qr):")
print(Q_np)
print("Матрица R (с использованием np.linalg.qr):")
print(R_np)


Начальная матрица:
[[-10   6   4]
 [  5 -10   3]
 [ -6   6   6]]
Матрица Q (метод Грама-Шмидта):
[[-0.78811041 -0.48757323 -0.37570511]
 [ 0.3940552  -0.86855151  0.30056409]
 [-0.47286624  0.08882913  0.87664525]]
Матрица R (метод Грама-Шмидта):
[[ 12.68857754 -11.50641193  -4.80747348]
 [  0.           6.29305049  -4.02297268]
 [  0.           0.           4.65874335]]
Результат перемножения Q и R (метод Грама-Шмидта):
[[-10.   6.   4.]
 [  5. -10.   3.]
 [ -6.   6.   6.]]
Матрица Q (с использованием np.linalg.qr):
[[-0.78811041 -0.48757323 -0.37570511]
 [ 0.3940552  -0.86855151  0.30056409]
 [-0.47286624  0.08882913  0.87664525]]
Матрица R (с использованием np.linalg.qr):
[[ 12.68857754 -11.50641193  -4.80747348]
 [  0.           6.29305049  -4.02297268]
 [  0.           0.           4.65874335]]
